### ISSUE TITLE
卡在牛牛页面无法进入主页，触屏无问题

### ISSUE THREAD

**Issue by Yeely0162** [Forairaaaaa/Chappie-II#5]
串口输出一切正常，触屏参数也能输出（解开注释了），初始化完成LVGL也提示初始化完成有psram信息输出，点触屏也不能进入主界面

**Comment by cyalive** [comment]
我也遇到同样的问题，求教题主是怎么解决的

**Comment by cyalive** [comment]
> 串口输出一切正常，触屏参数也能输出（解开注释了），初始化完成LVGL也提示初始化完成有psram信息输出，点触屏也不能进入主界面

求教（抱拳
